### ISSUE TITLE
First release roadmap (Oct. 2015)

### ISSUE THREAD

**Issue by juvenn** [leancloud/php-sdk#10]
##### Features to implement (in this release)

- [x] LeanObject: 对象存储
- [x] LeanQuery: 对象的查询，包括 $and, $or
- [x] LeanUser: 支持用户管理，包括第三方登录，邮箱，短信验证
- [x] LeanFile: 支持外部 URL 及上传到 Qiniu
- [x] LeanBytes: 支持二进制数据存储
- [x] IOperation: 支持 Set, Increment, Add, AddUnique, Remove 操作
- [x] LeanRelation: 支持对象关系的管理，包括添加与删除
- [x] CookieStorage and SessionStorage: 支持当前用户会话等临时信息的存储
- [x] LeanRelation: 支持建立关系的查询

##### Features for future release:

- [x] Exception needs to be carefully categorized and refactored
- [ ] Cloud function invoke
- [ ] GeoPoint and geo location query
- [ ] Role and ACL
- [ ] CQL query
- [ ] LeanEngine deployment

**Comment by juvenn** [comment]
与发布相关的 todo 包括：
- [ ] 官网上的 zip 包打包及下载
- [ ] 在 README 中添加更详细的使用指南
- [ ] demo 的开发

**Comment by jwfing** [comment]
zip 包是否通过七牛来分发？不要我们自己做下载点了。

**Comment by juvenn** [comment]
这个我准备参考目前官网下载的页面：https://leancloud.cn/docs/sdk_down.html，如 python-sdk? 具体的流程我还在了解。

**Comment by jwfing** [comment]
现在是从我们服务器下载，但是经常被开发者反应下载不下来，之前也说过把下载包都放到七牛，我觉得新的下载包还是直接放七牛好了，别让我们服务器称为瓶颈。

**Comment by juvenn** [comment]
- [x] #11 支持建立关系的查询

**Comment by juvenn** [comment]
- [x] #12 Exception needs to be carefully categorized and refactored

**Comment by juvenn** [comment]
已发布 0.1.0: https://github.com/leancloud/php-sdk/releases/tag/v0.1.0
